CI: gcovr: use --merge-mode-functions=merge-use-line-min, in sync with gcovr update from v5.2 to v8.3
Avoids govr errors with this code change (with arch-ci-linux-cuda-uni-pkgs):

AssertionError: Got function PetscStrHash(char const*) in /scratch/balay/petsc.x/include/petscsys.h on multiple lines: 2777, 2778.
        You can run gcovr with --merge-mode-functions=MERGE_MODE.