Increase sphinx version since previous version could not handle objects.inv in PETSc build
exception: '<' not supported between instances of 'dict' and 'dict') sphinx