Sys: fix PetscComplex
The old fix caused errors with deal.II wth g++11.3

/home/jczhang/dealii/include/deal.II/grid/tria_accessor.h:5701:39: error: ambiguous overload for 'operator!=' (operand types are 'const dealii::RefinementCase<2>' and 'dealii::RefinementPossibilities<2>::Possibilities')
 5701 |           Assert(this_refinement_case != RefinementCase<2>::no_refinement,
      |                  ~~~~~~~~~~~~~~~~~~~~ ^~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                  |                                          |
      |                  const dealii::RefinementCase<2>            dealii::RefinementPossibilities<2>::Possibilities
/home/jczhang/dealii/include/deal.II/base/exception_macros.h:563:17: note: in definition of macro 'Assert'
  563 |           if (!(cond))      \
      |                 ^~~~
/home/jczhang/dealii/include/deal.II/grid/tria_accessor.h:5701:39: note: candidate: 'operator!=(int, int)' (built-in)
 5701 |           Assert(this_refinement_case != RefinementCase<2>::no_refinement,
      |                  ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/jczhang/dealii/include/deal.II/base/exception_macros.h:563:17: note: in definition of macro 'Assert'
  563 |           if (!(cond))      \
      |                 ^~~~
In file included from /scratch/jczhang/petsc/include/petscsystypes.h:592,
                 from /scratch/jczhang/petsc/include/petscis.h:7,
                 from /home/jczhang/dealii/include/deal.II/base/index_set.h:47,
                 from /home/jczhang/dealii/include/deal.II/base/partitioner.h:23,
                 from /home/jczhang/dealii/include/deal.II/distributed/tria_base.h:24,
                 from /home/jczhang/dealii/include/deal.II/distributed/tria.h:27,
                 from /home/jczhang/dealii/source/distributed/p4est_wrappers.cc:17:
/scratch/jczhang/petsc/include/petsccxxcomplexfix.h:107:1: note: candidate: 'bool operator!=(const float&, const PetscComplex&)'
  107 | PETSC_CXX_COMPLEX_FIX(float)
      | ^~~~~~~~~~~~~~~~~~~~~
/scratch/jczhang/petsc/include/petsccxxcomplexfix.h:114:1: note: candidate: 'bool operator!=(const long double&, const PetscComplex&)'
  114 | PETSC_CXX_COMPLEX_FIX(long double)
      | ^~~~~~~~~~~~~~~~~~~~~
/scratch/jczhang/petsc/include/petsccxxcomplexfix.h:117:1: note: candidate: 'bool operator!=(const __float128&, const PetscComplex&)'
  117 | PETSC_CXX_COMPLEX_FIX(__float128)
      | ^~~~~~~~~~~~~~~~~~~~~
/scratch/jczhang/petsc/include/petsccxxcomplexfix.h:120:1: note: candidate: 'bool operator!=(const signed char&, const PetscComplex&)'

https://github.com/dealii/dealii/blob/master/include/deal.II/base/geometry_info.h#L779

template <int dim>
class RefinementCase : public RefinementPossibilities<dim>
{...}

template <int dim>
struct RefinementPossibilities
{
  enum Possibilities : std::uint8_t
  {
    no_refinement = 0,
    isotropic_refinement = 0xFF
  };
};