configure: fix C++ dialect detection with -Werror,-Wextra-semi-stmt
const auto [ab, cd, ef] = foobar(); // structured binding
;
  return 0;
}

              Output from compiling with  -std=c++17
/tmp/petsc-9qp5j607/config.setCompilers/conftest.cc:95:1: error: empty expression statement has no effect; remove unnecessary ';' to silence this warning [-Werror,-Wextra-semi-stmt]
   95 | ;
      | ^
1 error generated.

PETSc Error: No output file produced
              Rejecting compiler flag -std=c++17  due to nonzero status from link